export const TRENDING = {
  adverts_list: [
    {
      id: 8645147,
      is_boost: false,
      badge_info: {
        label: "TOP",
        slug: "top",
        bg_color: "#ffaf45",
        text_color: "#ffffff",
        aside_color: "#C8822C",
        service_type: "top",
      },
      paid_info: null,
      title: "Honda Civic 1.8 2007 Silver",
      date: "yesterday, 14:45",
      price: "33000",
      price_title: "GH₵ 33,000",
      user_id: 3370157,
      is_fav: false,
      is_owner: false,
      image:
        "https://pictures-ghana.jijistatic.com/32111658_MTgwLTI0MC1kYmU3NmMzZmRi.jpg",
      images_count: 10,
      url: "/weija/cars/honda-civic-1-8-2007-silver-CcGBbPhM1AMyURgm07RGmGB.html?page=1&pos=1&cur_pos=1&ads_per_page=20&ads_count=20&lid=uPJlNfYZMrcJcf-N",
    },
    {
      id: 8644449,
      is_boost: false,
      badge_info: {},
      paid_info: null,
      title: "Mitsubishi Lancer 2002 Gray",
      date: "yesterday, 06:39",
      price: "15000",
      price_title: "GH₵ 15,000",
      user_id: 2533245,
      is_fav: false,
      is_owner: false,
      image:
        "https://pictures-ghana.jijistatic.com/32214309_MTgwLTI0MC0yZDUyNWM5NTMz.jpg",
      images_count: 5,
      url: "/kumasi-metropolitan/cars/mitsubishi-lancer-2002-gray-q9axFWwnnYJ9lmWGxfsW61Sb.html?page=1&pos=2&cur_pos=2&ads_per_page=20&ads_count=20&lid=uPJlNfYZMrcJcf-N",
    },
    {
      id: 8676477,
      is_boost: false,
      badge_info: {},
      paid_info: null,
      title: "Toyota Corolla 1.8 Exclusive Automatic 2009 Brown",
      date: "yesterday, 23:50",
      price: "52000",
      price_title: "GH₵ 52,000",
      user_id: 4193615,
      is_fav: false,
      is_owner: false,
      image:
        "https://pictures-ghana.jijistatic.com/32251307_MTgwLTI0MC1hYmZhMzM2NDM0.jpg",
      images_count: 9,
      url: "/east-akim-municipal/cars/toyota-corolla-1-8-exclusive-automatic-2009-brown-loafIJPAIsNR3qCVYh2Gx7os.html?page=1&pos=3&cur_pos=3&ads_per_page=20&ads_count=20&lid=uPJlNfYZMrcJcf-N",
    },
    {
      id: 8677451,
      is_boost: "premium",
      badge_info: {
        label: "TOP+",
        slug: "booster",
        bg_color: "#00B53F",
        text_color: "#ffffff",
        aside_color: "#229826",
        service_type: "boost",
      },
      paid_info: {
        text: "Promoted",
      },
      title: "Kia Morning 2010 White",
      date: "yesterday, 12:32",
      price: "30000",
      price_title: "GH₵ 30,000",
      user_id: 2418656,
      is_fav: false,
      is_owner: false,
      image:
        "https://pictures-ghana.jijistatic.com/32239444_MTgwLTEzNS02MTkwNmFlMTI3.jpg",
      images_count: 7,
      url: "/taifa-burkina/cars/kia-morning-2010-white-e1NTUWJ1rwiu9vv8aaED7Xe3.html?page=1&pos=4&cur_pos=4&ads_per_page=20&ads_count=20&lid=uPJlNfYZMrcJcf-N",
    },
    {
      id: 8678326,
      is_boost: "premium",
      badge_info: {},
      paid_info: {
        text: "Promoted",
      },
      title: "Volkswagen Golf 1996 Orange",
      date: "yesterday, 15:22",
      price: "7500",
      price_title: "GH₵ 7,500",
      user_id: 1834201,
      is_fav: false,
      is_owner: false,
      image:
        "https://pictures-ghana.jijistatic.com/32243590_MTgwLTI0MC04M2JjZmZiNzM0.jpg",
      images_count: 9,
      url: "/kumasi-metropolitan/cars/volkswagen-golf-1996-orange-cTbMb1FYnuqS8kOg7bhWsOhf.html?page=1&pos=5&cur_pos=5&ads_per_page=20&ads_count=20&lid=uPJlNfYZMrcJcf-N",
    },
    {
      id: 8642049,
      is_boost: false,
      badge_info: {
        label: "TOP",
        slug: "top",
        bg_color: "#ffaf45",
        text_color: "#ffffff",
        aside_color: "#C8822C",
        service_type: "top",
      },
      paid_info: null,
      title: "Toyota Corolla 2010 Gray",
      date: "yesterday, 08:35",
      price: "55000",
      price_title: "GH₵ 55,000",
      user_id: 1902896,
      is_fav: false,
      is_owner: false,
      image:
        "https://pictures-ghana.jijistatic.com/32231687_MTgwLTEzNS03ZDQ5ZmJkODg2.jpg",
      images_count: 6,
      url: "/taifa-burkina/cars/toyota-corolla-2010-gray-dXfexaYh0i0CuMMr14FnzYTJ.html?page=1&pos=6&cur_pos=6&ads_per_page=20&ads_count=20&lid=uPJlNfYZMrcJcf-N",
    },
    {
      id: 8672501,
      is_boost: false,
      badge_info: {},
      paid_info: null,
      title: "Volkswagen Jetta 2.0 FSi Sportline 2008 Blue",
      date: "yesterday, 06:44",
      price: "27700",
      price_title: "GH₵ 27,700",
      user_id: 372060,
      is_fav: false,
      is_owner: false,
      image:
        "https://pictures-ghana.jijistatic.com/32217963_MTgwLTI0MC03MjI3OTVkMjgz.jpg",
      images_count: 17,
      url: "/obuasi-municipal/cars/volkswagen-jetta-2-0-fsi-sportline-2008-blue-Bs9A9ohWV7fMvtAJrj5EWvSh.html?page=1&pos=7&cur_pos=7&ads_per_page=20&ads_count=20&lid=uPJlNfYZMrcJcf-N",
    },
    {
      id: 8678901,
      is_boost: "vip_gold",
      badge_info: {},
      paid_info: {
        text: "Promoted",
      },
      title: "Toyota Corolla S 2006 White",
      date: "yesterday, 17:07",
      price: "45000",
      price_title: "GH₵ 45,000",
      user_id: 2114912,
      is_fav: false,
      is_owner: false,
      image:
        "https://pictures-ghana.jijistatic.com/32245973_MTgwLTEzNS01N2U1ZjYzZDYy.jpg",
      images_count: 6,
      url: "/circle/cars/toyota-corolla-s-2006-white-wddCkuvP4pSamcsapNQEIv9E.html?page=1&pos=8&cur_pos=8&ads_per_page=20&ads_count=20&lid=uPJlNfYZMrcJcf-N",
    },
    {
      id: 8675761,
      is_boost: false,
      badge_info: {
        label: "TOP",
        slug: "top",
        bg_color: "#ffaf45",
        text_color: "#ffffff",
        aside_color: "#C8822C",
        service_type: "top",
      },
      paid_info: null,
      title: "Nissan Hardbody 1999 Black",
      date: "yesterday, 14:40",
      price: "28000",
      price_title: "GH₵ 28,000",
      user_id: 2103284,
      is_fav: false,
      is_owner: false,
      image:
        "https://pictures-ghana.jijistatic.com/32244270_MTgwLTM5MC1jNGFkNGY4NTQ2.jpg",
      images_count: 5,
      url: "/awutu-senya/cars/nissan-hardbody-1999-black-z9TUgqd9yV0X2cQzBWO7Sonq.html?page=1&pos=9&cur_pos=9&ads_per_page=20&ads_count=20&lid=uPJlNfYZMrcJcf-N",
    },
    {
      id: 8654810,
      is_boost: false,
      badge_info: {},
      paid_info: null,
      title: "Volkswagen Golf 2000",
      date: "yesterday, 14:40",
      price: "12000",
      price_title: "GH₵ 12,000",
      user_id: 3082448,
      is_fav: false,
      is_owner: false,
      image:
        "https://pictures-ghana.jijistatic.com/32226681_MTgwLTMyMC02OWQxOGUxNzZj.jpg",
      images_count: 7,
      url: "/kumasi-metropolitan/cars/volkswagen-golf-2000-rpwqbV7aoX5W5n3NvzqlWIot.html?page=1&pos=10&cur_pos=10&ads_per_page=20&ads_count=20&lid=uPJlNfYZMrcJcf-N",
    },
    {
      id: 8666351,
      is_boost: "premium",
      badge_info: {
        label: "TOP+",
        slug: "booster",
        bg_color: "#00B53F",
        text_color: "#ffffff",
        aside_color: "#229826",
        service_type: "boost",
      },
      paid_info: {
        text: "Promoted",
      },
      title: "Kia Optima 2015 Gray",
      date: "27/06",
      price: "65000",
      price_title: "GH₵ 65,000",
      user_id: 1279264,
      is_fav: false,
      is_owner: false,
      image:
        "https://pictures-ghana.jijistatic.com/32195934_MTgwLTEzNS1kNjJiNjQwMmI2.jpg",
      images_count: 6,
      url: "/weija/cars/kia-optima-2015-gray-cLYYrmNGuMKtQERP4sI0q8ZY.html?page=1&pos=11&cur_pos=11&ads_per_page=20&ads_count=20&lid=uPJlNfYZMrcJcf-N",
    },
    {
      id: 8669971,
      is_boost: false,
      badge_info: {},
      paid_info: null,
      title: "Daewoo Kalos 1.4 SX Sedan 2004 Green",
      date: "yesterday, 06:44",
      price: "15000",
      price_title: "GH₵ 15,000",
      user_id: 326723,
      is_fav: false,
      is_owner: false,
      image:
        "https://pictures-ghana.jijistatic.com/32222063_MTgwLTM5OS1jMTBkNDMzZWY1.jpg",
      images_count: 8,
      url: "/new-juaben-municipal/cars/daewoo-kalos-1-4-sx-sedan-2004-green-8JNgCJiyvKXSHfuckOlZbzoZ.html?page=1&pos=12&cur_pos=12&ads_per_page=20&ads_count=20&lid=uPJlNfYZMrcJcf-N",
    },
    {
      id: 8660629,
      is_boost: "premium",
      badge_info: {
        label: "TOP+",
        slug: "booster",
        bg_color: "#00B53F",
        text_color: "#ffffff",
        aside_color: "#229826",
        service_type: "boost",
      },
      paid_info: {
        text: "Promoted",
      },
      title: "Mitsubishi Pajero 3.2 Di-D 2008 Gray",
      date: "26/06",
      price: "66000",
      price_title: "GH₵ 66,000",
      user_id: 2052057,
      is_fav: false,
      is_owner: false,
      image:
        "https://pictures-ghana.jijistatic.com/32168688_MTgwLTI0MC1hMjFmODkyZDdk.jpg",
      images_count: 5,
      url: "/accra-metropolitan/cars/mitsubishi-pajero-3-2-di-d-2008-gray-aWfU2MctvaDikpQwp4SOyjwL.html?page=1&pos=13&cur_pos=13&ads_per_page=20&ads_count=20&lid=uPJlNfYZMrcJcf-N",
    },
    {
      id: 7888536,
      is_boost: false,
      badge_info: {},
      paid_info: null,
      title: "Dodge Stratus Sedan RT 2006 Gray",
      date: "yesterday, 06:39",
      price: "18000",
      price_title: "GH₵ 18,000",
      user_id: 1389894,
      is_fav: false,
      is_owner: false,
      image:
        "https://pictures-ghana.jijistatic.com/32209029_MTgwLTEzNS03MjVhYWRmZGNj.jpg",
      images_count: 5,
      url: "/nkwanta-south/cars/dodge-stratus-sedan-rt-2006-gray-s4px5KR3HlO0GxEzOujb13GR.html?page=1&pos=14&cur_pos=14&ads_per_page=20&ads_count=20&lid=uPJlNfYZMrcJcf-N",
    },
    {
      id: 8676914,
      is_boost: "premium",
      badge_info: {},
      paid_info: {
        text: "Promoted",
      },
      title: "Nissan Sentra 2003 Silver",
      date: "yesterday, 14:48",
      price: "14500",
      price_title: "GH₵ 14,500",
      user_id: 797660,
      is_fav: false,
      is_owner: false,
      image:
        "https://pictures-ghana.jijistatic.com/32237089_MTgwLTI0MC1jZjEwYTllZTY2.jpg",
      images_count: 5,
      url: "/pokuase/cars/nissan-sentra-2003-silver-z5iWK67xkEPUybQb98O2c6PU.html?page=1&pos=15&cur_pos=15&ads_per_page=20&ads_count=20&lid=uPJlNfYZMrcJcf-N",
    },
    {
      id: 8550035,
      is_boost: false,
      badge_info: {
        label: "TOP",
        slug: "top",
        bg_color: "#ffaf45",
        text_color: "#ffffff",
        aside_color: "#C8822C",
        service_type: "top",
      },
      paid_info: null,
      title: "Kia Morning 2009 Gray",
      date: "27/06",
      price: "25000",
      price_title: "GH₵ 25,000",
      user_id: 1709614,
      is_fav: false,
      is_owner: false,
      image:
        "https://pictures-ghana.jijistatic.com/32198213_MTgwLTE4MC1iY2NhYzBhZmE4.jpg",
      images_count: 6,
      url: "/tema-metropolitan/cars/kia-morning-2009-gray-b4H2yEPKy6URY6VClyRNo8lO.html?page=1&pos=16&cur_pos=16&ads_per_page=20&ads_count=20&lid=uPJlNfYZMrcJcf-N",
    },
    {
      id: 8677097,
      is_boost: "premium",
      badge_info: {
        label: "TOP+",
        slug: "booster",
        bg_color: "#00B53F",
        text_color: "#ffffff",
        aside_color: "#229826",
        service_type: "boost",
      },
      paid_info: {
        text: "Promoted",
      },
      title: "Toyota Vitz 2010 Silver",
      date: "yesterday, 12:21",
      price: "33000",
      price_title: "GH₵ 33,000",
      user_id: 2418656,
      is_fav: false,
      is_owner: false,
      image:
        "https://pictures-ghana.jijistatic.com/32238357_MTgwLTI0MC0yMDE3NjkxNWI5.jpg",
      images_count: 5,
      url: "/taifa-burkina/cars/toyota-vitz-2010-silver-k86ky1A31qUd18lmBOQ1XiR6.html?page=1&pos=17&cur_pos=17&ads_per_page=20&ads_count=20&lid=uPJlNfYZMrcJcf-N",
    },
    {
      id: 8532896,
      is_boost: "premium",
      badge_info: {},
      paid_info: {
        text: "Promoted",
      },
      title: "Mercedes-Benz S-Class S 500 (W220) 2004 Black",
      date: "10/06",
      price: "70000",
      price_title: "GH₵ 70,000",
      user_id: 1756705,
      is_fav: false,
      is_owner: false,
      image:
        "https://pictures-ghana.jijistatic.com/31667755_MTgwLTIyNy1lNjhkYTE4ZjQy.jpg",
      images_count: 7,
      url: "/kumasi-metropolitan/cars/mercedes-benz-s-class-s-500-w220-2004-black-8c4VtcGPot50Jm1TOMFmiu5z.html?page=1&pos=18&cur_pos=18&ads_per_page=20&ads_count=20&lid=uPJlNfYZMrcJcf-N",
    },
    {
      id: 8127459,
      is_boost: false,
      badge_info: {
        label: "TOP",
        slug: "top",
        bg_color: "#ffaf45",
        text_color: "#ffffff",
        aside_color: "#C8822C",
        service_type: "top",
      },
      paid_info: null,
      title: "Hyundai Accent 2014 Gray",
      date: "yesterday, 20:40",
      price: "59000",
      price_title: "GH₵ 59,000",
      user_id: 2679191,
      is_fav: false,
      is_owner: false,
      image:
        "https://pictures-ghana.jijistatic.com/30105254_MTgwLTI0MC1jNzA1NzUzYTRh.jpg",
      images_count: 8,
      url: "/east-legon/cars/hyundai-accent-2014-gray-wgZ9jQG8OmuXDJQyo6ahnggK.html?page=1&pos=19&cur_pos=19&ads_per_page=20&ads_count=20&lid=uPJlNfYZMrcJcf-N",
    },
    {
      id: 8608802,
      is_boost: "premium",
      badge_info: {},
      paid_info: {
        text: "Promoted",
      },
      title: "Mitsubishi Mirage 2015 Orange",
      date: "21/06",
      price: "50000",
      price_title: "GH₵ 50,000",
      user_id: 2804982,
      is_fav: false,
      is_owner: false,
      image:
        "https://pictures-ghana.jijistatic.com/31972675_MTgwLTI0MC1jNTA2ZWFiZGRl.jpg",
      images_count: 5,
      url: "/achimota/cars/mitsubishi-mirage-2015-orange-gGNgJi3OZRCLQYH09WeGBTh.html?page=1&pos=20&cur_pos=20&ads_per_page=20&ads_count=20&lid=uPJlNfYZMrcJcf-N",
    },
    {
      id: 8673521,
      is_boost: false,
      badge_info: {},
      paid_info: null,
      title: "Toyota Wish 2012 White",
      date: "27/06",
      price: "88000",
      price_title: "GH₵ 88,000",
      user_id: 387647,
      is_fav: false,
      is_owner: false,
      image:
        "https://pictures-ghana.jijistatic.com/32222389_MTgwLTEzNS0yZGY5ZmY1MTg1.jpg",
      images_count: 5,
      url: "/kumasi-metropolitan/cars/toyota-wish-2012-white-5joFYLNQA5dQ3yhzA9NsTgBn.html?page=1&pos=21&cur_pos=21&ads_per_page=20&ads_count=20&lid=uPJlNfYZMrcJcf-N",
    },
    {
      id: 8646202,
      is_boost: "premium",
      badge_info: {},
      paid_info: {
        text: "Promoted",
      },
      title: "Hyundai Accent GLS 2011 White",
      date: "26/06",
      price: "43000",
      price_title: "GH₵ 43,000",
      user_id: 3280352,
      is_fav: false,
      is_owner: false,
      image:
        "https://pictures-ghana.jijistatic.com/32112181_MTgwLTE4MC05NTQ0ZWZjNWI5.jpg",
      images_count: 8,
      url: "/nungua/cars/hyundai-accent-gls-2011-white-yxTUWCcgBu4u8e9RRYVJTGce.html?page=1&pos=22&cur_pos=22&ads_per_page=20&ads_count=20&lid=uPJlNfYZMrcJcf-N",
    },
    {
      id: 8669332,
      is_boost: false,
      badge_info: {},
      paid_info: null,
      title: "Apple iPhone 11 128 GB White",
      date: "yesterday, 07:31",
      price: "1500",
      price_title: "GH₵ 1,500",
      user_id: 3143285,
      is_fav: false,
      is_owner: false,
      image:
        "https://pictures-ghana.jijistatic.com/32204382_MTgwLTIxMC0yNmZkY2YwNGMxLTE.jpg",
      images_count: 3,
      url: "/madina/mobile-phones/apple-iphone-11-128-gb-white-7IolN3GmqRUwnRsNWfndRiD1.html?page=1&pos=23&cur_pos=23&ads_per_page=20&ads_count=20&lid=uPJlNfYZMrcJcf-N",
    },
    {
      id: 8677826,
      is_boost: "diamond",
      badge_info: {
        label: "3X Diamond",
        slug: "booster_diamond_multi",
        bg_color: "#00B53F",
        text_color: "#ffffff",
        aside_color: "#229826",
        service_type: "boost",
      },
      paid_info: {
        text: "Promoted",
      },
      title: "Apple iPhone XS Max 256 GB Black",
      date: "yesterday, 13:37",
      price: "2200",
      price_title: "GH₵ 2,200",
      user_id: 1318919,
      is_fav: false,
      is_owner: false,
      image:
        "https://pictures-ghana.jijistatic.com/32241418_MTgwLTI0MC02MzRkODI1YThm.jpg",
      images_count: 6,
      url: "/accra-metropolitan/mobile-phones/apple-iphone-xs-max-256-gb-black-BN8qyn8GwwuHUSqtA5EBviU9.html?page=1&pos=24&cur_pos=24&ads_per_page=20&ads_count=20&lid=uPJlNfYZMrcJcf-N",
    },
    {
      id: 8676267,
      is_boost: false,
      badge_info: {},
      paid_info: null,
      title: "Apple iPhone 12 mini 64 GB Purple",
      date: "yesterday, 10:11",
      price: "2750",
      price_title: "GH₵ 2,750",
      user_id: 3260908,
      is_fav: false,
      is_owner: false,
      image:
        "https://pictures-ghana.jijistatic.com/32236192_MTgwLTI0MC1iNDVlOWY0ZDkw.jpg",
      images_count: 2,
      url: "/teshie/mobile-phones/apple-iphone-12-mini-64-gb-purple-83BV51tuLkXtw1iSl2pNzP5M.html?page=1&pos=25&cur_pos=25&ads_per_page=20&ads_count=20&lid=uPJlNfYZMrcJcf-N",
    },
    {
      id: 8663754,
      is_boost: false,
      badge_info: {},
      paid_info: null,
      title: "Apple iPhone X 64 GB White",
      date: "27/06",
      price: "1500",
      price_title: "GH₵ 1,500",
      user_id: 2462942,
      is_fav: false,
      is_owner: false,
      image:
        "https://pictures-ghana.jijistatic.com/32208222_MTgwLTI0MC0xZjVlMTJhYmU1.jpg",
      images_count: 3,
      url: "/kumasi-metropolitan/mobile-phones/apple-iphone-x-64-gb-white-nyXJc6VtKVzTmCA4EbYCtANe.html?page=1&pos=26&cur_pos=26&ads_per_page=20&ads_count=20&lid=uPJlNfYZMrcJcf-N",
    },
    {
      id: 8668958,
      is_boost: false,
      badge_info: {},
      paid_info: null,
      title: "Apple iPhone 7 Plus 128 GB Black",
      date: "yesterday, 06:52",
      price: "900",
      price_title: "GH₵ 900",
      user_id: 2491995,
      is_fav: false,
      is_owner: false,
      image:
        "https://pictures-ghana.jijistatic.com/32231254_MTgwLTI0MC1iMzJkNjBkYzM4.jpg",
      images_count: 3,
      url: "/madina/mobile-phones/apple-iphone-7-plus-128-gb-black-XwiJEOwxWuQvofNM6Nn53rW.html?page=1&pos=27&cur_pos=27&ads_per_page=20&ads_count=20&lid=uPJlNfYZMrcJcf-N",
    },
    {
      id: 8669108,
      is_boost: false,
      badge_info: {},
      paid_info: null,
      title: "Samsung Galaxy S8 64 GB Black",
      date: "yesterday, 07:18",
      price: "650",
      price_title: "GH₵ 650",
      user_id: 3658147,
      is_fav: false,
      is_owner: false,
      image:
        "https://pictures-ghana.jijistatic.com/32203563_MTgwLTEzNS0xODUyOWQ2NDE3.jpg",
      images_count: 2,
      url: "/ashaiman-municipal/mobile-phones/samsung-galaxy-s8-64-gb-black-zrlomAdEiUeu5d92IwL3WDaV.html?page=1&pos=28&cur_pos=28&ads_per_page=20&ads_count=20&lid=uPJlNfYZMrcJcf-N",
    },
    {
      id: 8665613,
      is_boost: false,
      badge_info: {},
      paid_info: null,
      title: "Apple iPhone 11 128 GB Green",
      date: "27/06",
      price: "2900",
      price_title: "GH₵ 2,900",
      user_id: 2667505,
      is_fav: false,
      is_owner: false,
      image:
        "https://pictures-ghana.jijistatic.com/32189967_MTgwLTI0MC0xMWNlYjNjNjE3.jpg",
      images_count: 2,
      url: "/tesano/mobile-phones/apple-iphone-11-128-gb-green-5R91VuBiDeJQIIPRuBsYRbzd.html?page=1&pos=29&cur_pos=29&ads_per_page=20&ads_count=20&lid=uPJlNfYZMrcJcf-N",
    },
    {
      id: 8549942,
      is_boost: false,
      badge_info: {},
      paid_info: null,
      title: "Samsung Galaxy A12 128 GB Red",
      date: "yesterday, 05:00",
      price: "1000",
      price_title: "GH₵ 1,000",
      user_id: 3175678,
      is_fav: false,
      is_owner: false,
      image:
        "https://pictures-ghana.jijistatic.com/32225484_MTgwLTI0MC0yMGQ1ZWI4Y2Qx.jpg",
      images_count: 3,
      url: "/gbawe/mobile-phones/samsung-galaxy-a12-128-gb-red-unJGYrbbWzyso9bNycd6Mvtc.html?page=1&pos=30&cur_pos=30&ads_per_page=20&ads_count=20&lid=uPJlNfYZMrcJcf-N",
    },
    {
      id: 8628327,
      is_boost: false,
      badge_info: {},
      paid_info: null,
      title: "Apple iPhone 11 64 GB Red",
      date: "22/06",
      price: "2650",
      price_title: "GH₵ 2,650",
      user_id: 2687164,
      is_fav: false,
      is_owner: false,
      image:
        "https://pictures-ghana.jijistatic.com/32044331_MTgwLTI0MC03MWJjNThhMDU3.jpg",
      images_count: 3,
      url: "/madina/mobile-phones/apple-iphone-11-64-gb-red-802jyob3nHSvOgR74WZKNdFJ.html?page=1&pos=31&cur_pos=31&ads_per_page=20&ads_count=20&lid=uPJlNfYZMrcJcf-N",
    },
    {
      id: 8611214,
      is_boost: "premium",
      badge_info: {},
      paid_info: {
        text: "Promoted",
      },
      title: "Samsung Galaxy Note 20 Ultra 5G 256 GB Black",
      date: "26/06",
      price: "3600",
      price_title: "GH₵ 3,600",
      user_id: 2231800,
      is_fav: false,
      is_owner: false,
      image:
        "https://pictures-ghana.jijistatic.com/31985795_MTgwLTI0MC02ZTRlMjljZTgy.jpg",
      images_count: 5,
      url: "/pokuase/mobile-phones/samsung-galaxy-note-20-ultra-5g-256-gb-black-CcoCFeS8DYl4nXs2tpRVhvsR.html?page=1&pos=32&cur_pos=32&ads_per_page=20&ads_count=20&lid=uPJlNfYZMrcJcf-N",
    },
    {
      id: 8569290,
      is_boost: false,
      badge_info: {},
      paid_info: null,
      title: "Xiaomi Redmi Note 9 128 GB Blue",
      date: "today, 06:00",
      price: "1050",
      price_title: "GH₵ 1,050",
      user_id: 4047935,
      is_fav: false,
      is_owner: false,
      image:
        "https://pictures-ghana.jijistatic.com/31889212_MTgwLTI0MC1jNzUxYjViMWU5.jpg",
      images_count: 2,
      url: "/nungua/mobile-phones/xiaomi-redmi-note-9-128-gb-blue-wHuRyCWZCHTZEnq5b89GC8z2.html?page=1&pos=33&cur_pos=33&ads_per_page=20&ads_count=20&lid=uPJlNfYZMrcJcf-N",
    },
    {
      id: 8528588,
      is_boost: false,
      badge_info: {},
      paid_info: null,
      title: "Apple iPhone 11 64 GB Green",
      date: "today, 07:15",
      price: "2600",
      price_title: "GH₵ 2,600",
      user_id: 1539139,
      is_fav: false,
      is_owner: false,
      image:
        "https://pictures-ghana.jijistatic.com/32235867_MTgwLTI0MC1mMGQ0MDMyN2Uz.jpg",
      images_count: 2,
      url: "/nungua/mobile-phones/apple-iphone-11-64-gb-green-iUIgm7UfzbaaQc1ruM1F2wIU.html?page=1&pos=34&cur_pos=34&ads_per_page=20&ads_count=20&lid=uPJlNfYZMrcJcf-N",
    },
    {
      id: 8583475,
      is_boost: false,
      badge_info: {},
      paid_info: null,
      title: "Apple iPhone X 64 GB Black",
      date: "yesterday, 11:44",
      price: "1750",
      price_title: "GH₵ 1,750",
      user_id: 3750760,
      is_fav: false,
      is_owner: false,
      image:
        "https://pictures-ghana.jijistatic.com/31889375_MTgwLTI4MS00MjY0MjRkY2Nh.jpg",
      images_count: 4,
      url: "/obuasi-municipal/mobile-phones/apple-iphone-x-64-gb-black-62mn13wgvnkPxHhnqijHZF2w.html?page=1&pos=35&cur_pos=35&ads_per_page=20&ads_count=20&lid=uPJlNfYZMrcJcf-N",
    },
    {
      id: 8661688,
      is_boost: false,
      badge_info: {},
      paid_info: null,
      title: "Apple iPhone 12 Pro 128 GB Blue",
      date: "27/06",
      price: "3000",
      price_title: "GH₵ 3,000",
      user_id: 1501045,
      is_fav: false,
      is_owner: false,
      image:
        "https://pictures-ghana.jijistatic.com/32199662_MTgwLTI0MC0xOGVlNWI4YmFj.jpg",
      images_count: 2,
      url: "/shama-ahanta-east-metropolitan/mobile-phones/apple-iphone-12-pro-128-gb-blue-7pvS4OnOXYf4PggqTMaP0ucE.html?page=1&pos=36&cur_pos=36&ads_per_page=20&ads_count=20&lid=uPJlNfYZMrcJcf-N",
    },
    {
      id: 8398821,
      is_boost: false,
      badge_info: {},
      paid_info: null,
      title: "Tecno Spark 4 32 GB Purple",
      date: "25/06",
      price: "400",
      price_title: "GH₵ 400",
      user_id: 2879393,
      is_fav: false,
      is_owner: false,
      image:
        "https://pictures-ghana.jijistatic.com/31942680_MTgwLTI0MC1hMGY0MjczNGEw.jpg",
      images_count: 4,
      url: "/north-industrial-area/mobile-phones/tecno-spark-4-32-gb-purple-BXfppyFLpk6qbOZoWuxIoYmP.html?page=1&pos=37&cur_pos=37&ads_per_page=20&ads_count=20&lid=uPJlNfYZMrcJcf-N",
    },
    {
      id: 8660442,
      is_boost: false,
      badge_info: {},
      paid_info: null,
      title: "Apple iPhone X 256 GB White",
      date: "26/06",
      price: "2000",
      price_title: "GH₵ 2,000",
      user_id: 3913173,
      is_fav: false,
      is_owner: false,
      image:
        "https://pictures-ghana.jijistatic.com/32168298_MTgwLTI0MC0yYjJlOWViMzNl.jpg",
      images_count: 4,
      url: "/tema-metropolitan/mobile-phones/apple-iphone-x-256-gb-white-ufhQVqB6idfAXW0Ovg3d1oHc.html?page=1&pos=38&cur_pos=38&ads_per_page=20&ads_count=20&lid=uPJlNfYZMrcJcf-N",
    },
    {
      id: 8539225,
      is_boost: "diamond",
      badge_info: {
        label: "Diamond",
        slug: "booster_diamond",
        bg_color: "#00B53F",
        text_color: "#ffffff",
        aside_color: "#229826",
        service_type: "boost",
      },
      paid_info: {
        text: "Promoted",
      },
      title: "New Tecno Phantom V Fold 512 GB",
      date: "22/06",
      price: "11900",
      price_title: "GH₵ 11,900",
      user_id: 2066183,
      is_fav: false,
      is_owner: false,
      image:
        "https://pictures-ghana.jijistatic.com/32059307_MTgwLTI0MC03MmY1NzY5Y2Y3.jpg",
      images_count: 4,
      url: "/accra-metropolitan/mobile-phones/new-tecno-phantom-v-fold-512-gb-nP6Ifzw5VQTJ5x41RhBfdVUC.html?page=1&pos=39&cur_pos=39&ads_per_page=20&ads_count=20&lid=uPJlNfYZMrcJcf-N",
    },
    {
      id: 8606996,
      is_boost: false,
      badge_info: {},
      paid_info: null,
      title: "Apple iPhone 7 32 GB Gray",
      date: "20/06",
      price: "800",
      price_title: "GH₵ 800",
      user_id: 2093628,
      is_fav: false,
      is_owner: false,
      image:
        "https://pictures-ghana.jijistatic.com/31986338_MTgwLTMyMC0zMWFhZGJmZTAw.jpg",
      images_count: 2,
      url: "/agbogba/mobile-phones/apple-iphone-7-32-gb-gray-rO4O4CoEZNI85KQCWIQkij0P.html?page=1&pos=40&cur_pos=40&ads_per_page=20&ads_count=20&lid=uPJlNfYZMrcJcf-N",
    },
    {
      id: 8591004,
      is_boost: false,
      badge_info: {},
      paid_info: null,
      title: "Apple iPhone XS Max 512 GB Black",
      date: "17/06",
      price: "3000",
      price_title: "GH₵ 3,000",
      user_id: 1407153,
      is_fav: false,
      is_owner: false,
      image:
        "https://pictures-ghana.jijistatic.com/31906710_MTgwLTI0MC0wOTI4OGVhOWYw.jpg",
      images_count: 5,
      url: "/madina/mobile-phones/apple-iphone-xs-max-512-gb-black-yEbqtKRcRbKKagsa0Tl3J48J.html?page=1&pos=41&cur_pos=41&ads_per_page=20&ads_count=20&lid=uPJlNfYZMrcJcf-N",
    },
    {
      id: 8622126,
      is_boost: false,
      badge_info: {},
      paid_info: null,
      title: "Apple iPhone 11 64 GB Purple",
      date: "today, 06:44",
      price: "2800",
      price_title: "GH₵ 2,800",
      user_id: 1902602,
      is_fav: false,
      is_owner: false,
      image:
        "https://pictures-ghana.jijistatic.com/32026786_MTgwLTI0MC0wNjZkZTgyYjZj.jpg",
      images_count: 2,
      url: "/kumasi-metropolitan/mobile-phones/apple-iphone-11-64-gb-purple-abZRd3iNIvXmOOflf7lpFrsR.html?page=1&pos=42&cur_pos=42&ads_per_page=20&ads_count=20&lid=uPJlNfYZMrcJcf-N",
    },
    {
      id: 8532483,
      is_boost: "premium",
      badge_info: {},
      paid_info: {
        text: "Promoted",
      },
      title: "Apple iPhone 14 128 GB Blue",
      date: "14/06",
      price: "5200",
      price_title: "GH₵ 5,200",
      user_id: 2002758,
      is_fav: false,
      is_owner: false,
      image:
        "https://pictures-ghana.jijistatic.com/31666059_MTgwLTI1Ni0yNWU2N2JmNTYyLTE.jpg",
      images_count: 2,
      url: "/accra-metropolitan/mobile-phones/apple-iphone-14-128-gb-blue-pU4j4OgqkKRY0q6IN0jMWIIj.html?page=1&pos=43&cur_pos=43&ads_per_page=20&ads_count=20&lid=uPJlNfYZMrcJcf-N",
    },
    {
      id: 8365735,
      is_boost: false,
      badge_info: {},
      paid_info: null,
      title: "Samsung Galaxy Note 9 128 GB Blue",
      date: "18/06",
      price: "1450",
      price_title: "GH₵ 1,450",
      user_id: 1220580,
      is_fav: false,
      is_owner: false,
      image:
        "https://pictures-ghana.jijistatic.com/31027892_MTgwLTI0MC1jYWE2NmUxMGQw.jpg",
      images_count: 2,
      url: "/tema-metropolitan/mobile-phones/samsung-galaxy-note-9-128-gb-blue-cE5C8CJrOTJOURKcSj2oScL1.html?page=1&pos=44&cur_pos=44&ads_per_page=20&ads_count=20&lid=uPJlNfYZMrcJcf-N",
    },
    {
      id: 8674216,
      is_boost: "vip",
      badge_info: {},
      paid_info: {
        text: "Promoted",
      },
      title: "Furnished 1bdrm Apartment in Ablekuma for rent",
      date: "yesterday, 10:21",
      price: "300",
      price_title: "GH₵ 300 per month",
      user_id: 389697,
      is_fav: false,
      is_owner: false,
      image:
        "https://pictures-ghana.jijistatic.com/32225372_MTgwLTI0MC1hZWRiYmIwNDQx.jpg",
      images_count: 16,
      url: "/ablekuma/houses-apartments-for-rent/furnished-1bdrm-apartment-in-ablekuma-for-rent-yqce66xPm73qZAB9ZlS7ENiH.html?page=1&pos=45&cur_pos=45&ads_per_page=20&ads_count=20&lid=uPJlNfYZMrcJcf-N",
    },
    {
      id: 8675186,
      is_boost: false,
      badge_info: {},
      paid_info: null,
      title: "1bdrm Apartment in Trusted Estate, McCarthy Hill for rent",
      date: "yesterday, 11:11",
      price: "500",
      price_title: "GH₵ 500 per month",
      user_id: 3002531,
      is_fav: false,
      is_owner: false,
      image:
        "https://pictures-ghana.jijistatic.com/32228735_MTgwLTE4MC03OTU0YWNiZTAx.jpg",
      images_count: 5,
      url: "/mccarthy-hill/houses-apartments-for-rent/1bdrm-apartment-in-trusted-estate-mccarthy-hill-for-rent-tm4A1AuUXLOgnoAbfY52Wl7.html?page=1&pos=46&cur_pos=46&ads_per_page=20&ads_count=20&lid=uPJlNfYZMrcJcf-N",
    },
    {
      id: 8648851,
      is_boost: "vip_gold",
      badge_info: {},
      paid_info: {
        text: "Promoted",
      },
      title: "1bdrm Apartment in Ladt Lagon, New Legon for rent",
      date: "yesterday, 06:15",
      price: "700",
      price_title: "GH₵ 700 per month",
      user_id: 1136916,
      is_fav: false,
      is_owner: false,
      image:
        "https://pictures-ghana.jijistatic.com/32230062_MTgwLTI0MC04NzE3NjA3ZmIw.jpg",
      images_count: 12,
      url: "/new-legon/houses-apartments-for-rent/1bdrm-apartment-in-ladt-lagon-new-legon-for-rent-muleLangrUl262e5c1UF3k9I.html?page=1&pos=47&cur_pos=47&ads_per_page=20&ads_count=20&lid=uPJlNfYZMrcJcf-N",
    },
    {
      id: 8677790,
      is_boost: "vip_gold",
      badge_info: {},
      paid_info: {
        text: "Promoted",
      },
      title: "1bdrm Apartment in Old Barrier Kings for rent",
      date: "yesterday, 13:46",
      price: "450",
      price_title: "GH₵ 450 per month",
      user_id: 1319942,
      is_fav: false,
      is_owner: false,
      image:
        "https://pictures-ghana.jijistatic.com/32242307_MTgwLTI0MC1kOTRkODk4MWE2.jpg",
      images_count: 18,
      url: "/west-hills-mall/houses-apartments-for-rent/1bdrm-apartment-in-old-barrier-kings-for-rent-oz5iOPkft9Wg5P67ymDHfFPe.html?page=1&pos=48&cur_pos=48&ads_per_page=20&ads_count=20&lid=uPJlNfYZMrcJcf-N",
    },
    {
      id: 8672545,
      is_boost: false,
      badge_info: {},
      paid_info: null,
      title: "1bdrm Room & Parlour in Seth, Kwashieman for rent",
      date: "yesterday, 12:32",
      price: "200",
      price_title: "GH₵ 200 per month",
      user_id: 1550651,
      is_fav: false,
      is_owner: false,
      image:
        "https://pictures-ghana.jijistatic.com/32217951_MTgwLTI0MC03NTA1MDMzMDE2.jpg",
      images_count: 5,
      url: "/kwashieman/houses-apartments-for-rent/1bdrm-room-parlour-in-seth-kwashieman-for-rent-lxMClyFXYCMMt7x1bcABLp9.html?page=1&pos=49&cur_pos=49&ads_per_page=20&ads_count=20&lid=uPJlNfYZMrcJcf-N",
    },
    {
      id: 8673237,
      is_boost: "vip_gold",
      badge_info: {},
      paid_info: {
        text: "Promoted",
      },
      title: "1bdrm House in Rockshell Properties, Madina for rent",
      date: "yesterday, 07:54",
      price: "320",
      price_title: "GH₵ 320 per month",
      user_id: 2508639,
      is_fav: false,
      is_owner: false,
      image:
        "https://pictures-ghana.jijistatic.com/32221006_MTgwLTI0MC1lNjk3N2IyNjJi.jpg",
      images_count: 8,
      url: "/madina/houses-apartments-for-rent/1bdrm-house-in-rockshell-properties-madina-for-rent-kLPeJV9GggJVaSm0NdgQ2JP7.html?page=1&pos=50&cur_pos=50&ads_per_page=20&ads_count=20&lid=uPJlNfYZMrcJcf-N",
    },
    {
      id: 8670825,
      is_boost: false,
      badge_info: {},
      paid_info: null,
      title: "1bdrm Apartment in Maxspinno Properties, East Legon for rent",
      date: "27/06",
      price: "850",
      price_title: "GH₵ 850 per month",
      user_id: 141331,
      is_fav: false,
      is_owner: false,
      image:
        "https://pictures-ghana.jijistatic.com/32210429_MTgwLTEzNS00YjI2YzU5YTQz.jpg",
      images_count: 8,
      url: "/east-legon/houses-apartments-for-rent/1bdrm-apartment-in-maxspinno-properties-east-legon-for-rent-tSPzuaCc277K3yTEIr1qBW7.html?page=1&pos=51&cur_pos=51&ads_per_page=20&ads_count=20&lid=uPJlNfYZMrcJcf-N",
    },
    {
      id: 8678941,
      is_boost: false,
      badge_info: {},
      paid_info: null,
      title: "2bdrm Apartment in Kumasi Metropolitan for rent",
      date: "yesterday, 16:11",
      price: "500",
      price_title: "GH₵ 500 per month",
      user_id: 1293945,
      is_fav: false,
      is_owner: false,
      image:
        "https://pictures-ghana.jijistatic.com/32246280_MTgwLTI0MC0yNTA3ZjViNDI1.jpg",
      images_count: 14,
      url: "/kumasi-metropolitan/houses-apartments-for-rent/2bdrm-apartment-in-kumasi-metropolitan-for-rent-ARi3kJuoHfA0BMkvaPHUw4GG.html?page=1&pos=52&cur_pos=52&ads_per_page=20&ads_count=20&lid=uPJlNfYZMrcJcf-N",
    },
    {
      id: 8670200,
      is_boost: false,
      badge_info: {},
      paid_info: null,
      title: "1bdrm Apartment in Ga West Municipal for rent",
      date: "yesterday, 08:17",
      price: "350",
      price_title: "GH₵ 350 per month",
      user_id: 1932628,
      is_fav: false,
      is_owner: false,
      image:
        "https://pictures-ghana.jijistatic.com/32207957_MTgwLTQwMC1iMjg3Mzk5MmM3.jpg",
      images_count: 5,
      url: "/ga-west-municipal/houses-apartments-for-rent/1bdrm-apartment-in-ga-west-municipal-for-rent-1gmyAO3m3ba6LYQ8HLDIUn4A.html?page=1&pos=53&cur_pos=53&ads_per_page=20&ads_count=20&lid=uPJlNfYZMrcJcf-N",
    },
    {
      id: 8667995,
      is_boost: "vip",
      badge_info: {},
      paid_info: {
        text: "Promoted",
      },
      title: "2bdrm Apartment in Ike, Awoshie for rent",
      date: "27/06",
      price: "800",
      price_title: "GH₵ 800 per month",
      user_id: 3173880,
      is_fav: false,
      is_owner: false,
      image:
        "https://pictures-ghana.jijistatic.com/32213152_MTgwLTI0MC0yNGY3N2I0MTNi.jpg",
      images_count: 11,
      url: "/awoshie/houses-apartments-for-rent/2bdrm-apartment-in-ike-awoshie-for-rent-8ownDP5VscoIXaOutIp2DzU1.html?page=1&pos=54&cur_pos=54&ads_per_page=20&ads_count=20&lid=uPJlNfYZMrcJcf-N",
    },
    {
      id: 8663180,
      is_boost: "diamond",
      badge_info: {},
      paid_info: {
        text: "Promoted",
      },
      title: "1bdrm Shared Apartment in Alex Otuo Properties, Atwima Nwabiagya",
      date: "27/06",
      price: "145",
      price_title: "GH₵ 145 per month",
      user_id: 2649222,
      is_fav: false,
      is_owner: false,
      image:
        "https://pictures-ghana.jijistatic.com/32179561_MTgwLTI0MC04YTczYTJlMzdm.jpg",
      images_count: 5,
      url: "/atwima-nwabiagya/houses-apartments-for-rent/1bdrm-shared-apartment-in-alex-otuo-properties-atwima-nwabiagya-37O1l0hlnXWBS4VnLwSwYoQ7.html?page=1&pos=55&cur_pos=55&ads_per_page=20&ads_count=20&lid=uPJlNfYZMrcJcf-N",
    },
    {
      id: 8675636,
      is_boost: "diamond",
      badge_info: {},
      paid_info: {
        text: "Promoted",
      },
      title: "Studio Apartment in Nana Williams, East Legon for rent",
      date: "yesterday, 06:51",
      price: "600",
      price_title: "GH₵ 600 per month",
      user_id: 4101944,
      is_fav: false,
      is_owner: false,
      image:
        "https://pictures-ghana.jijistatic.com/32230873_MTgwLTEzNS02YjI5NTY2ODdl.jpg",
      images_count: 7,
      url: "/east-legon/houses-apartments-for-rent/studio-apartment-in-nana-williams-east-legon-for-rent-u9gupqG3gDliscLXT0eRMxJ2.html?page=1&pos=56&cur_pos=56&ads_per_page=20&ads_count=20&lid=uPJlNfYZMrcJcf-N",
    },
    {
      id: 7379209,
      is_boost: "vip",
      badge_info: {},
      paid_info: {
        text: "Promoted",
      },
      title: "1bdrm Apartment in Achimota Around The, Overhead for rent",
      date: "23/06",
      price: "900",
      price_title: "GH₵ 900 per month",
      user_id: 2020601,
      is_fav: false,
      is_owner: false,
      image:
        "https://pictures-ghana.jijistatic.com/27113327_MTgwLTI0MC1jZTY2OWRlOWJl.jpg",
      images_count: 9,
      url: "/overhead/houses-apartments-for-rent/1bdrm-apartment-in-achimota-around-the-overhead-for-rent-CpIdmUDaXtkpJeG82t5GNEM9.html?page=1&pos=57&cur_pos=57&ads_per_page=20&ads_count=20&lid=uPJlNfYZMrcJcf-N",
    },
    {
      id: 8671500,
      is_boost: "vip_gold",
      badge_info: {
        label: "VIP TOP+",
        slug: "booster_vip",
        bg_color: "#00B53F",
        text_color: "#ffffff",
        aside_color: "#229826",
        service_type: "boost",
      },
      paid_info: {
        text: "Promoted",
      },
      title: "1bdrm Apartment in Dome for rent",
      date: "27/06",
      price: "500",
      price_title: "GH₵ 500 per month",
      user_id: 4119460,
      is_fav: false,
      is_owner: false,
      image:
        "https://pictures-ghana.jijistatic.com/32218205_MTgwLTIyNy02NmQxZWJhNjQx.jpg",
      images_count: 6,
      url: "/dome/houses-apartments-for-rent/1bdrm-apartment-in-dome-for-rent-nv3ioObvI2mSgKeLvSIgwikJ.html?page=1&pos=58&cur_pos=58&ads_per_page=20&ads_count=20&lid=uPJlNfYZMrcJcf-N",
    },
    {
      id: 8673798,
      is_boost: false,
      badge_info: {},
      paid_info: null,
      title: "1bdrm Apartment in Weija Junction for rent",
      date: "27/06",
      price: "500",
      price_title: "GH₵ 500 per month",
      user_id: 3120022,
      is_fav: false,
      is_owner: false,
      image:
        "https://pictures-ghana.jijistatic.com/32223511_MTgwLTEzNS01MjFkMjE4ZDI5.jpg",
      images_count: 7,
      url: "/weija-junction/houses-apartments-for-rent/1bdrm-apartment-in-weija-junction-for-rent-laAEKNOB19oLJsacJMGJIHy7.html?page=1&pos=59&cur_pos=59&ads_per_page=20&ads_count=20&lid=uPJlNfYZMrcJcf-N",
    },
    {
      id: 8649508,
      is_boost: "diamond",
      badge_info: {
        label: "Diamond",
        slug: "booster_diamond",
        bg_color: "#00B53F",
        text_color: "#ffffff",
        aside_color: "#229826",
        service_type: "boost",
      },
      paid_info: {
        text: "Promoted",
      },
      title: "1bdrm Apartment in Mccarthy Hill, Accra Metropolitan for rent",
      date: "24/06",
      price: "400",
      price_title: "GH₵ 400 per month",
      user_id: 2587838,
      is_fav: false,
      is_owner: false,
      image:
        "https://pictures-ghana.jijistatic.com/32124686_MTgwLTI0MC05MmZhNTJhZTg2.jpg",
      images_count: 5,
      url: "/accra-metropolitan/houses-apartments-for-rent/1bdrm-apartment-in-mccarthy-hill-accra-metropolitan-for-rent-sbjGDgpxWjWDZhdjclehQB0f.html?page=1&pos=60&cur_pos=60&ads_per_page=20&ads_count=20&lid=uPJlNfYZMrcJcf-N",
    },
  ],
  listing_id: "uPJlNfYZMrcJcf-N",
  status: "ok",
};
export const CATEGORIES = [
  {
    name: "Trending",
    key: 657,
    icon: "trending",
  },
  {
    name: "Vehicles",
    key: 6,
    icon: "vehicles",
  },
  {
    name: "Property",
    key: 9,
    icon: "property",
  },
  {
    name: "Mobile Phones & Tablets",
    key: 1,
    icon: "mobilephonestablets",
  },
  {
    name: "Electronics",
    key: 3,
    icon: "electronics",
  },
  {
    name: "Home, Furniture & Appliances",
    key: 4,
    icon: "homefurnitureappliances",
  },
  {
    name: "Health & Beauty",
    key: 27,
    icon: "healthbeauty",
  },
  {
    name: "Fashion",
    key: 5,
    icon: "fashion",
  },
  {
    name: "Sports, Arts & Outdoors",
    key: 8,
    icon: "sportsartsoutdoors",
  },
  {
    name: "Seeking Work CVs",
    key: 110,
    icon: "seekingworkcvs",
  },
  {
    name: "Services",
    key: 140,
    icon: "services",
  },
  {
    name: "Jobs",
    key: 47,
    icon: "jobs",
  },
  {
    name: "Babies & Kids",
    key: 59,
    icon: "babieskids",
  },
  {
    name: "Animals & Pets",
    key: 7,
    icon: "animalspets",
  },
  {
    name: "Agriculture & Food",
    key: 24,
    icon: "agriculturefood",
  },
  {
    name: "Commercial Equipment & Tools",
    key: 23,
    icon: "commercialequipmenttools",
  },
  {
    name: "Repair & Construction",
    key: 290,
    icon: "repairconstruction",
  },
];

export default function generateArrayOfObjects(length) {
  var arr = [];

  for (var i = 1; i <= length; i++) {
    var obj = {
      key: i,
      name: `Card ${i}`,
    };

    arr.push(obj);
  }

  return arr;
}
